"""Side-effect-free declaration/value models used by Machine-Soul."""

from .application import (
    Application,
    ConfigurationFile,
    Operation,
    Platform,
    PlatformDeclaration,
    Support,
)
from .context import ConflictPolicy, OperationContext, TargetAccount
from .discovery import (
    DiscoveryObservation,
    EvidenceStrength,
    InstallationAssessment,
    InstallationCandidate,
    InstallationOwnership,
    InstallationPresence,
    InstallationScope,
    ObservationAuthority,
    TriState,
    VerificationAssessment,
    VerificationConclusion,
    VerificationObservation,
)
from .result import OperationResult, ResultStatus
from .strategies import (
    AptPackage,
    BuiltInExecutableDiscovery,
    DpkgPackageDiscovery,
    ExecutableDiscovery,
    InstallationDiscoveryPlan,
    CustomConfiguration,
    CustomInstaller,
    CustomVerification,
    ConfigurationVerificationPlan,
    HomeRelativeDestination,
    LocalAppDataRelativeDestination,
    PowerShellProfileDestination,
    RemoteInstallScript,
    StandaloneBinary,
    WindowsAppxDiscovery,
    WindowsArpDiscovery,
    WindowsPosixHomeDestination,
    WindowsPosixPackageDiscovery,
    WindowsTerminalSettingsDestination,
    WingetPackage,
    WingetPackageDiscovery,
)

__all__ = [
    "Application",
    "ConfigurationFile",
    "Operation",
    "Platform",
    "PlatformDeclaration",
    "Support",
    "ConflictPolicy",
    "OperationContext",
    "TargetAccount",
    "DiscoveryObservation",
    "EvidenceStrength",
    "InstallationAssessment",
    "InstallationCandidate",
    "InstallationOwnership",
    "InstallationPresence",
    "InstallationScope",
    "ObservationAuthority",
    "TriState",
    "VerificationAssessment",
    "VerificationConclusion",
    "VerificationObservation",
    "OperationResult",
    "ResultStatus",
    "AptPackage",
    "BuiltInExecutableDiscovery",
    "DpkgPackageDiscovery",
    "ExecutableDiscovery",
    "InstallationDiscoveryPlan",
    "CustomConfiguration",
    "CustomInstaller",
    "CustomVerification",
    "ConfigurationVerificationPlan",
    "HomeRelativeDestination",
    "LocalAppDataRelativeDestination",
    "PowerShellProfileDestination",
    "RemoteInstallScript",
    "StandaloneBinary",
    "WindowsAppxDiscovery",
    "WindowsArpDiscovery",
    "WindowsPosixHomeDestination",
    "WindowsPosixPackageDiscovery",
    "WindowsTerminalSettingsDestination",
    "WingetPackage",
    "WingetPackageDiscovery",
]
