name: Machine-Soul validation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/machine_soul_validation_linux.yml

  windows:
    uses: ./.github/workflows/machine_soul_validation_windows.yml

  fresh-linux:
    uses: ./.github/workflows/machine_soul_validation_fresh_linux.yml

  fresh-windows:
    uses: ./.github/workflows/machine_soul_validation_fresh_windows.yml
